#docker build --platform linux/amd64 -t kore-http-sqlite:amd64 --target amd64 -f ./Dockerfile.sqlite . 
#docker build --platform linux/arm64 -t kore-http-sqlite:arm64 --target arm64 -f ./Dockerfile.sqlite . 

# Etapa de compilación para AMD64
FROM rust:1.78-slim-buster AS builder-amd64
RUN rustup target add x86_64-unknown-linux-gnu
COPY . .
RUN cargo build --target x86_64-unknown-linux-gnu --release

# Etapa de compilación para ARM64
FROM rust:1.78-slim-buster AS builder-arm64
RUN rustup target add aarch64-unknown-linux-gnu
COPY . .
RUN cargo build --target aarch64-unknown-linux-gnu --release

# Imagen final para AMD64
FROM rust:1.78-slim-buster AS amd64
COPY --from=builder-amd64 /target/x86_64-unknown-linux-gnu/release/kore-http /usr/local/bin/kore-http
RUN rustup target add wasm32-unknown-unknown

CMD ["kore-http"]

# Imagen final para ARM64
FROM rust:1.78-slim-buster AS arm64
COPY --from=builder-arm64 /target/aarch64-unknown-linux-gnu/release/kore-http /usr/local/bin/kore-http
RUN rustup target add wasm32-unknown-unknown

CMD ["kore-http"]


# Etapa de compilación para AMD64
# FROM rust:1.78-slim-buster AS builder-amd64
# WORKDIR /app
# RUN rustup target add x86_64-unknown-linux-gnu
# COPY . .
# RUN cargo build --target x86_64-unknown-linux-gnu --release

# Etapa de compilación para ARM64
# FROM rust:1.78-slim-buster AS builder-arm64
# RUN rustup target add aarch64-unknown-linux-gnu
# COPY . .
# RUN cargo build --target aarch64-unknown-linux-gnu --release

# Imagen final para AMD64
# FROM gcr.io/distroless/cc-debian12 AS amd64
# COPY --from=builder-amd64 /target/x86_64-unknown-linux-gnu/release/kore-http /usr/local/bin/kore-http
# CMD ["kore-http"]

# Imagen final para ARM64
# FROM gcr.io/distroless/cc-debian12 AS arm64
# COPY --from=builder-arm64 /target/aarch64-unknown-linux-gnu/release/kore-http /usr/local/bin/kore-http
# CMD ["kore-http"]